package isc_tap_act_15_20550380;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edgar 
 */
public class Table_Update extends javax.swing.JFrame {

    Connection conex = null;
    Icon i = new ImageIcon(getClass().getResource("v1.png"));
    String IDL_T, ISBN_T, T_T, D_T, AP_T, IDA_T, IDG_T;

    /**
     * Creates new form Table
     */
    public Table_Update() {
        initComponents();
        setLocationRelativeTo(null);

        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jTable1.getSelectedRow() != -1) {
                    int fila = jTable1.getSelectedRow();

                    txt_IDL.setText(jTable1.getValueAt(fila, 0).toString());
                    txt_ISBN.setText(jTable1.getValueAt(fila, 1).toString());
                    txt_Titulo.setText(jTable1.getValueAt(fila, 2).toString());
                    txt_Desc.setText(jTable1.getValueAt(fila, 3).toString());
                    txt_AP1.setText(jTable1.getValueAt(fila, 4).toString());
                    txt_IDA.setText(jTable1.getValueAt(fila, 5).toString());
                    txt_IDG.setText(jTable1.getValueAt(fila, 6).toString());
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_IDA = new javax.swing.JTextField();
        txt_IDL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ISBN = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Titulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Desc = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txt_IDG = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnS1 = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_AP1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_IDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IDAKeyTyped(evt);
            }
        });
        getContentPane().add(txt_IDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 110, -1));

        txt_IDL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IDLKeyTyped(evt);
            }
        });
        getContentPane().add(txt_IDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 90, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("ID Autor:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 70, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("ID LIbro:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("ISBN:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, 20));

        txt_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ISBNActionPerformed(evt);
            }
        });
        txt_ISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ISBNKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 200, -1));

        jButton4.setText("←");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Titulo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 20));

        txt_Titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TituloKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 400, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Descripción:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, 20));

        txt_Desc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DescKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 400, 60));

        jButton3.setText("GUARDAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        txt_IDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IDGKeyTyped(evt);
            }
        });
        getContentPane().add(txt_IDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 110, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("ID Género:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 90, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Año de Publicación:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 140, 20));

        btnS1.setText("MOSTRAR TABLA");
        btnS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 150, 40));

        btnS.setText("ACTUALIZAR");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });
        getContentPane().add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 150, 40));

        jLabel3.setText("realizar los cambios que dese y por ultimo solo de click en guardar y actualizar para visualizar todo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 570, 20));

        jLabel2.setText("Para editar un registro seleccionelo en la tabla, los datos apareceran en los capmos de abajo y en ellos podra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 630, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 550, 180));
        getContentPane().add(txt_AP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 150, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
 jTable1.setModel(new DefaultTableModel());  
 try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conex = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_libros", "root", "Millie2002");
            Statement st = conex.createStatement();
            ResultSet res = st.executeQuery("select * from libro");
            ResultSetMetaData rsmd = res.getMetaData();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            int columnas = rsmd.getColumnCount();
            String[] columNomb = new String[columnas];
            for (int i = 0; i < columnas; i++) {
                columNomb[i] = rsmd.getColumnName(i + 1);
            }
            model.setColumnIdentifiers(columNomb);

            String ID_Libro, ISBN, Titulo, Descripción, Año_Public, ID_Autor, ID_Genero;
            while (res.next()) {
                ID_Libro = res.getString(1);
                ISBN = res.getString(2);
                Titulo = res.getString(3);
                Descripción = res.getString(4);
                Año_Public = res.getString(5);
                ID_Autor = res.getString(6);
                ID_Genero = res.getString(7);

                String[] fila = {ID_Libro, ISBN, Titulo, Descripción, Año_Public, ID_Autor, ID_Genero};
                model.addRow(fila);
            }
            st.close();
            conex.close();

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: No se elimino el registro" + e, "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSActionPerformed

    private void btnS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conex = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_libros", "root", "Millie2002");
            Statement st = conex.createStatement();
            ResultSet res = st.executeQuery("select * from libro");
            ResultSetMetaData rsmd = res.getMetaData();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            int columnas = rsmd.getColumnCount();
            String[] columNomb = new String[columnas];
            for (int i = 0; i < columnas; i++) {
                columNomb[i] = rsmd.getColumnName(i + 1);
            }
            model.setColumnIdentifiers(columNomb);

            String ID_Libro, ISBN, Titulo, Descripción, Año_Public, ID_Autor, ID_Genero;
            while (res.next()) {
                ID_Libro = res.getString(1);
                ISBN = res.getString(2);
                Titulo = res.getString(3);
                Descripción = res.getString(4);
                Año_Public = res.getString(5);
                ID_Autor = res.getString(6);
                ID_Genero = res.getString(7);

                String[] fila = {ID_Libro, ISBN, Titulo, Descripción, Año_Public, ID_Autor, ID_Genero};
                model.addRow(fila);
            }
            st.close();
            conex.close();

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: No se elimino el registro" + e, "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnS1ActionPerformed

    private void txt_IDLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IDLKeyTyped
        char validar = evt.getKeyChar();  //Validar para ingreso exclusivo de numeros
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo números por favor", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_IDLKeyTyped

    private void txt_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ISBNActionPerformed

    private void txt_ISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ISBNKeyTyped
        char validar = evt.getKeyChar();  //Validar para ingreso exclusivo de numeros
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo números por favor", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_ISBNKeyTyped

    private void txt_TituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TituloKeyTyped
        char validar = evt.getKeyChar();  //Validar para ingreso exclusivo de letras
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras por favor", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_TituloKeyTyped

    private void txt_DescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescKeyTyped
        char validar = evt.getKeyChar();  //Validar para ingreso exclusivo de letras
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras por favor", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_DescKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        IDL_T = txt_IDL.getText(); //Guardamos lo introducido en el txt en nuestro string temporal
        ISBN_T = txt_ISBN.getText();
        T_T = txt_Titulo.getText();
        D_T = txt_Desc.getText();
        AP_T = txt_AP1.getText();
        IDA_T = txt_IDA.getText();
        IDG_T = txt_IDG.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conex = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_libros", "root", "Millie2002");
            PreparedStatement st;
            String ID = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            st = conex.prepareStatement("UPDATE bd_libros.libro SET ID_Libro=?,ISBN=?,Titulo=?,Descripción=?,Año_Public=?,ID_Autor=?,ID_Genero=? WHERE ID_Libro= '" + ID + "'");

            st.setString(1, IDL_T);
            st.setString(2, ISBN_T);
            st.setString(3, T_T);
            st.setString(4, D_T);
            st.setString(5, AP_T);
            st.setString(6, IDA_T);
            st.setString(7, IDG_T);

            int res = st.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Datos modificados", "", JOptionPane.PLAIN_MESSAGE, i);
            }
            conex.close();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: No se modifico correctamente" + e, "", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_IDGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IDGKeyTyped
        char validar = evt.getKeyChar();  //Validar para ingreso exclusivo de numeros
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo números por favor", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_IDGKeyTyped

    private void txt_IDAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IDAKeyTyped
        char validar = evt.getKeyChar();  //Validar para ingreso exclusivo de numeros
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo números por favor", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_IDAKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        MENU s = new MENU();
        s.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnS1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_AP1;
    public javax.swing.JTextField txt_Desc;
    public javax.swing.JTextField txt_IDA;
    public javax.swing.JTextField txt_IDG;
    public javax.swing.JTextField txt_IDL;
    public javax.swing.JTextField txt_ISBN;
    public javax.swing.JTextField txt_Titulo;
    // End of variables declaration//GEN-END:variables
}
